### ISSUE TITLE
Change title cell style?

### ISSUE THREAD

**Issue by simonqbs** [Arch/FluentExcel#12]
Hi!
Is it possible to change title cell style in an easy way? Currently it is hardcoded in IEnumerableNpoiExtensions.cs.

**Comment by rigofunc** [comment]
Good suggestion, disable style setting or change the background/foreground color?

**Comment by simonqbs** [comment]
Both options would be good to have, and also what kind of fill pattern to use maybe.

**Comment by mrtylerzhou** [comment]
I have the same question,the checker header style does't looks very good.It is better that user can customize or by default remove it.

**Comment by rigofunc** [comment]
This weekend will release a version for fixing this issues

**Comment by mrtylerzhou** [comment]
Also address another small problem,when use the toExcelContent extension method to export excel file as attachment,it is ok to set the extension as xlsx, but to set it as xls,when open the exported file,excel will give an alert that the file is corrupted or unsafe,do you want to open it anyway?.Though the file itself is not corrupted at all and everything just fine when open it.but the alert is annoying.I do not know whether you have ever came across with this problem,i guess that maybe the same content(xxx.toExcencontent) treated as both xls and xlsx cause the problem.

**Comment by rigofunc** [comment]
Had a fix  for this. Use following code to disable title cell style
```csharp
Excel.Setting.TitleCellStyleApplier = null;
```

**Comment by rigofunc** [comment]
@simonqbs @mrtylerzhou [v1.2.2](https://www.nuget.org/packages/FluentExcel/1.2.2) had been released for fixing this issues

**Comment by rigofunc** [comment]
@mrtylerzhou 

> Also address another small problem,when use the toExcelContent extension method to export excel file as attachment,it is ok to set the extension as xlsx, but to set it as xls,when open the exported file,excel will give an alert that the file is corrupted or unsafe,do you want to open it anyway?.Though the file itself is not corrupted at all and everything just fine when open it.but the alert is annoying.I do not know whether you have ever came across with this problem,i guess that maybe the same content(xxx.toExcencontent) treated as both xls and xlsx cause the problem.

this fix release not solve this issues

**Comment by mrtylerzhou** [comment]
thanks for your clarification

**Comment by rigofunc** [comment]
Could I close this issue now? or more feedback for fine tunning?

**Comment by rigofunc** [comment]
@simonqbs Following code solve your problem or you have any better solution? if yes, please PR
```csharp
Excel.Setting.TitleCellStyleApplier = yourTitleCellStyleApplier
```

**Comment by simonqbs** [comment]
Nice work! Now it will be much easier to change styles :-)

**Comment by simonqbs** [comment]
I created a PR with docs on how to use the functionality.

**Comment by rigofunc** [comment]
Thanks
