### ISSUE TITLE
无法确定的列该如何获取?

### ISSUE THREAD

**Issue by JHeLiu** [Arch/FluentExcel#14]
1、当我获取一个 Excel 表格，但是我无法确定它有多少列, 应该如何准确的获取它。我尽可能需要获取 标题头。
2、如何导出 DataTable 以及 dynamic 类型的数据

**Comment by rigofunc** [comment]
POCO的属性名跟表头名字一样就可以了，不用任何配置，可以加载出来。暂时不支持导出 DataTable 以及 dynamic 类型的数据

**Comment by rigofunc** [comment]
个人不喜欢DataTable相关的API，所以不打算支持。
