### ISSUE TITLE
导出的excel可以按多个列来合并单元格吗

### ISSUE THREAD

**Issue by zhujinhu21** [Arch/FluentExcel#18]
![qq 20180127113920](https://user-images.githubusercontent.com/4327149/35468342-c978f7be-0356-11e8-8288-00eac2b0d771.png)

我需要按照姓名和出诊日期来合并，我使用fluentexcel导出的excel
![896](https://user-images.githubusercontent.com/4327149/35468382-5f7a7800-0357-11e8-83ca-f34e173e47a0.png)

**Comment by rigofunc** [comment]
Of course. Please read the README first.

**Comment by zhujinhu21** [comment]
@xyting 我看过readme使用说明，没找到怎么设置，是IsMergeEnabled？

**Comment by rigofunc** [comment]
yes

**Comment by rigofunc** [comment]
You can also see the sample code

**Comment by zhujinhu21** [comment]
但是导出的excel是我第二张图的效果，实际上我需要第一张图的效果（姓名和出诊日期是做为合并的依据）

**Comment by zhujinhu21** [comment]
只有姓名和出诊日期相同的才合并

**Comment by rigofunc** [comment]
终于看懂你的问题了。

但是，目前不支持这个特性。

**Comment by rigofunc** [comment]
你可以提交一个PR支持这个特性。
