### ISSUE TITLE
Support to configure the max row count per sheet

### ISSUE THREAD

**Issue by rigofunc** [Arch/FluentExcel#2]
Currently, all the data will be save to one sheet, but, if the data is very very large, the excel maybe throw OutOfMemoryException, so SHOULD provides some methods to split the data to multiple sheets.

**Comment by magicmoux** [comment]
Hi,
First of all, thank you for making this library, it's a very good base for a real fluent excel Api.
I added extensions to solve this issue in [PR#10](https://github.com/Arch/FluentExcel/pull/10)

Thanks for your conideration
Max.

**Comment by rigofunc** [comment]
@magicmoux Thanks very much!
