### ISSUE TITLE
版本

### ISSUE THREAD

**Issue by JHeLiu** [Arch/FluentExcel#24]
不对.NET更新了吗? 而专注 Core 更新吗？

**Comment by rigofunc** [comment]
都支持呀

**Comment by JHeLiu** [comment]
更新到 2.2.0.0 会升级我的 System.Net.Http 版本 ？

**Comment by rigofunc** [comment]
因为是.netstandard的原因。但问题是升级` System.Net.Http `会带来什么问题？

**Comment by JHeLiu** [comment]
因为WEBAPI项目默认是在C盘 会引用一个 4.0版本的，如果升级后，它会引用我开发工具下面的一个新的 版本号 4.2 的，如果我使用 NuGet 来获取 system.net.http 版本号。它加入项目是 4.1.但是我升级后 它就会自动引用 到开发工具下面的 4.2版本，这会导致整个项目编译冲突。 尽管它可能不带来正式影响，但是看到警告 会担心 想不到的错误发生

**Comment by JHeLiu** [comment]
还有，我想问一下，它支持直接返回流的 API操作吗？因为我很多时候想 直接下载到 客户端

**Comment by xyting** [comment]
目前API不支持Stream

**Comment by JHeLiu** [comment]
可以考虑加入这个功能吗？

**Comment by rigofunc** [comment]
> 因为WEBAPI项目默认是在C盘 会引用一个 4.0版本的，如果升级后，它会引用我开发工具下面的一个新的 版本号 4.2 的，如果我使用 NuGet 来获取 system.net.http 版本号。它加入项目是 4.1.但是我升级后 它就会自动引用 到开发工具下面的 4.2版本，这会导致整个项目编译冲突。 尽管它可能不带来正式影响，但是看到警告 会担心 想不到的错误发生

那就回退到上一版本

**Comment by rigofunc** [comment]
> 还有，我想问一下，它支持直接返回流的 API操作吗？因为我很多时候想 直接下载到 客户端

不对，有支持流的API，请仔细看一下api

**Comment by JHeLiu** [comment]
好的 3Q 我会抽时间 看一下，

**Comment by JHeLiu** [comment]
@xyting  返回 byte 字节 的 API？

**Comment by rigofunc** [comment]
@JHeLiu See [this](https://github.com/Arch/FluentExcel/blob/develop/src/Extensions/IEnumerableNpoiExtensions.cs#L38) for more information

**Comment by JHeLiu** [comment]
@xyting  3Q
