### ISSUE TITLE
Lot of modification basing on your code

### ISSUE THREAD

**Issue by biggray** [Arch/FluentExcel#25]
Hello, I'd like to let you know that I'd like to do a lot of modification basing on your code soon. The main purpose is to mitigate the performance issue of NPOI while processing large excel file. I'm currently considering using EPPlus or something else as the underlying layer. And I may also do other changes too.
So here to make you aware of it. And I'd like to also know from you that if it's OK to still use the word "FluentExcel" in the name of this mentioned new project or should I choose another name?

Glad to hear from you. Thank you.

**Comment by rigofunc** [comment]
Happy your choose, using `FluentExcel` if you like

**Comment by biggray** [comment]
OK. Got it. Thank you very much! :)
