### ISSUE TITLE
Class has AutoIndex setting can't be exported

### ISSUE THREAD

**Issue by ldsenow** [Arch/FluentExcel#6]
as per title and exception is Invalid column index (-1). I guess is the config index is -1 when AutoIndex is set to ture

**Comment by rigofunc** [comment]
Currently, the `auto index` only used for importing. I'll fix next release, right now, you need to configure the index by code.

**Comment by rigofunc** [comment]
The bug had been fixed, but the nuget package have not release.

**Comment by rigofunc** [comment]
see [v1.2.0](https://www.nuget.org/packages/FluentExcel/1.2.0)
