### ISSUE TITLE
Designing a extension point for easy extend the exist functionalities.

### ISSUE THREAD

**Issue by rigofunc** [Arch/FluentExcel#8]
Designing a extension point for easy extend the exist functionalities. Such as `FromAnnotations()` like @tupunco done.

**Comment by tupunco** [comment]
Thought that this project only focus on the use of `Fluent API`, do not accept the `Annotation` function, so no "PR".

**Comment by rigofunc** [comment]
I had fork your idea, see the README for more info, but I impl it by extension method.

**Comment by tupunco** [comment]
At first I would also like to not modify the existing code to complete the "FromAnnotations" function, but found that the lack of authority, so the fork and modify the code.

**Comment by rigofunc** [comment]
Yes, the extension point was added after you forked, but right now you can use the new released version. BTW, the AdjustAutoIndex method has a bug, PR welcome to fix it.
